### ISSUE TITLE
Hero stop moving when courier deliver some wards

### ISSUE THREAD

**Issue by Usera2** [jeffhill/Dota2#520]
### Description

If you are on the move to plant a ward, and in the mean time courier deliver you some wards, your hero will stop moving and cancel that ward planting job.

**Comment by Ahimtar** [comment]
This is because the item you are interacting with can change to a different item. An interesting situation, for example:
1) You have 1 sentry ward in your inventory and attempt to place it
2) Courier delivers you 1 observer ward - this switches the item to "observer and sentry wards", set to observer
What should happen now? It feels weird to be able to place a sentry ward even though the item itself is toggled on observer wards. (this happened to me a while ago, see video (ignore my voice pls): https://youtu.be/7jlH8WjhyRo?t=219 )
I still think it should be fixed somehow but it's not as clearcut as it may seem.

**Comment by tlhsglkc** [comment]
This is still happening in 2026 and there is a second, more serious side effect.

When the courier delivers wards while you are in the middle of placing a ward, two things happen:

1. The ward placement action is cancelled
2. The shared Observer/Sentry slot switches to Observer if an Observer is delivered

This forces the player to re-click, but now the active ward type has changed, so the wrong ward is placed.

This is not just “hero stops moving”. It is an action cancellation + item state change that causes incorrect gameplay.

Repro example:
Match ID: 8636426895
Player: Smart Water (Skywrath Mage)
Time: 4:20 to 4:35

At 4:31 I clicked to place a ward. Courier delivered an Observer immediately after, cancelling the action and switching the ward slot. When I pressed the same key again, an Observer was placed instead of the intended ward.

This is especially common in Turbo due to fast courier delivery.

Video showing this happening: https://github.com/user-attachments/assets/d2513bff-cbfc-4706-adb8-677a15ff9a9f
